clear all;
power_mats = extractCSVs('pow_2weeks*.csv',1);
pf_mats = extractCSVs('pf_2weeks*.csv',1);
wind_size = 1;

%%have to flipud somehow

% for i=1:size(power_mats,3)
%    mean_day = mean(power_mats(:,7,i));
%    power_mats(:,7,i) = power_mats(:,7,i) - mean_day;
% end
% 
% for i=1:size(pf_mats,3)
%    mean_day = mean(pf_mats(:,7,i));
%    pf_mats(:,7,i) = pf_mats(:,7,i) - mean_day;
% end


for i=1:size(power_mats,3)
    pow_mats_mean(:,i) = windowMat(power_mats(:,:,i),'mean',wind_size,i);
    pow_mats_range(:,i) = windowMat(power_mats(:,:,i),'range',wind_size,i);
    pow_mats_peak(:,i) = windowMat(power_mats(:,:,i),'peak',wind_size,i);
    mats_hrs(:,i) = windowMat(power_mats(:,:,i),'hour',wind_size,i);
end

for i=1:size(pf_mats,3)
    pf_mats_mean(:,i) = windowMat(pf_mats(:,:,i),'mean',wind_size,i);
    pf_mats_range(:,i) = windowMat(pf_mats(:,:,i),'range',wind_size,i);
    pf_mats_peak(:,i) = windowMat(pf_mats(:,:,i),'peak',wind_size,i);
end


occup524 = [processOccupCSV('5_24_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_24_gtruth.csv',wind_size,'binary',5)];
occup525 = [processOccupCSV('5_25_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_25_gtruth.csv',wind_size,'binary',5)];
occup526 = [processOccupCSV('5_26_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_26_gtruth.csv',wind_size,'binary',5)];
occup527 = [processOccupCSV('5_27_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_27_gtruth.csv',wind_size,'binary',5)];
occup528 = [processOccupCSV('5_28_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_28_gtruth.csv',wind_size,'binary',5)];
occup529 = [processOccupCSV('5_29_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_29_gtruth.csv',wind_size,'binary',5)];
occup530 = [processOccupCSV('5_30_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_30_gtruth.csv',wind_size,'binary',5)];
occup531 = [processOccupCSV('5_31_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('5_31_gtruth.csv',wind_size,'binary',5)];
occup61 = [processOccupCSV('6_1_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('6_1_gtruth.csv',wind_size,'binary',5)];
occup62 = [processOccupCSV('6_2_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('6_2_gtruth.csv',wind_size,'binary',5)];
occup63 = [processOccupCSV('6_3_gtruth.csv',wind_size,'coarse',[0,1,2,4,8]) processOccupCSV('6_3_gtruth.csv',wind_size,'binary',5)];

occup_mat = vertcat(occup524,occup525,occup526,occup527,occup528,...
    occup529,occup530,occup531,occup61,occup62,occup63);

%%%Light vectors
Light24 = [ones(20*60+56,1);zeros(1440-(20*60+56),1)];
Light25 = [zeros(6*60+8,1);ones((20*60+19)-(6*60+8),1);zeros(1440-(20*60+19),1)];
Light26 = [zeros(11*60+43,1);ones((16*60+27)-(11*60+43),1);zeros(1440-(16*60+27),1)];
Light27 = [zeros(5*60+56,1);ones((22*60+44)-(5*60+56),1);zeros(1440-(22*60+44),1)];
Light28 = [zeros(9*60+19,1);ones((20*60+44)-(9*60+19),1);zeros(1440-(20*60+44),1)];
Light29 = [zeros(7*60+26,1);ones((19*60+12)-(7*60+26),1);zeros(1440-(19*60+12),1)];
Light30 = [zeros(7*60+35,1);ones((22*60+55)-(7*60+35),1);zeros(1440-(22*60+55),1)];
Light31 = [zeros(8*60+47,1);ones((20*60+45)-(8*60+47),1);zeros((21*60+2)-(20*60+45),1);...    
    ones(1440-(21*60+2),1)];
Light1 = [ones((20*60+45),1);zeros(1440-(20*60+45),1)];
Light2 = [zeros(17*60+9,1);ones((19*60+59)-(17*60+9),1);zeros(1440-(19*60+59),1)];
Light3 = [zeros(9*60+23,1);ones((22*60+11)-(9*60+23),1);zeros((22*60+14)-(22*60+11),1);...
    ones((22*60+28)-(22*60+14),1);zeros((1440)-(22*60+28),1)];

Light_mat = downsample(vertcat(Light24,Light25,Light26,Light27,Light28,...
    Light29,Light30,Light31,Light1,Light2,Light3),wind_size);


big_mat = [flipud(pow_mats_mean) flipud(pow_mats_range) flipud(pow_mats_peak) ...
    flipud(pf_mats_mean) flipud(pf_mats_range) flipud(pf_mats_peak) Light_mat mats_hrs(:,1) occup_mat];


big_mat(any(big_mat==100,2),:)=[];

big_mat = [big_mat(:,1:end-1) circshift(big_mat(:,end),3)];


filename = 'Shifted_3.arff';
fid = fopen(filename, 'w');
fprintf(fid,'%s\n\n','@RELATION Occupancy');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute m1 Numeric', ...
    '@Attribute m2 Numeric','@Attribute m3 Numeric','@Attribute m4 Numeric', ...
    '@Attribute m5 Numeric','@Attribute m6 Numeric','@Attribute m7 Numeric', ... 
    '@Attribute m8 Numeric','@Attribute m9 Numeric','@Attribute m10 Numeric', ...
    '@Attribute m11 Numeric','@Attribute m12 Numeric','@Attribute m13 Numeric', ...
    '@Attribute m14 Numeric','@Attribute m15 Numeric','@Attribute m16 Numeric', ...
    '@Attribute m17 Numeric','@Attribute m18 Numeric','@Attribute m19 Numeric', ...
    '@Attribute m20 Numeric','@Attribute m21 Numeric');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute r1 Numeric', ...
    '@Attribute r2 Numeric','@Attribute r3 Numeric','@Attribute r4 Numeric', ...
    '@Attribute r5 Numeric','@Attribute r6 Numeric','@Attribute r7 Numeric', ... 
    '@Attribute r8 Numeric','@Attribute r9 Numeric','@Attribute r10 Numeric', ...
    '@Attribute r11 Numeric','@Attribute r12 Numeric','@Attribute r13 Numeric', ...
    '@Attribute r14 Numeric','@Attribute r15 Numeric','@Attribute r16 Numeric', ...
    '@Attribute r17 Numeric','@Attribute r18 Numeric','@Attribute r19 Numeric', ...
    '@Attribute r20 Numeric','@Attribute r21 Numeric');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute p1 Numeric', ...
    '@Attribute p2 Numeric','@Attribute p3 Numeric','@Attribute p4 Numeric', ...
    '@Attribute p5 Numeric','@Attribute p6 Numeric','@Attribute p7 Numeric', ... 
    '@Attribute p8 Numeric','@Attribute p9 Numeric','@Attribute p10 Numeric', ...
    '@Attribute p11 Numeric','@Attribute p12 Numeric','@Attribute p13 Numeric', ...
    '@Attribute p14 Numeric','@Attribute p15 Numeric','@Attribute p16 Numeric', ...
    '@Attribute p17 Numeric','@Attribute p18 Numeric','@Attribute p19 Numeric', ...
    '@Attribute p20 Numeric','@Attribute p21 Numeric');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute pfm1 Numeric', ...
    '@Attribute pfm2 Numeric','@Attribute pfm3 Numeric','@Attribute pfm4 Numeric', ...
    '@Attribute pfm5 Numeric','@Attribute pfm6 Numeric','@Attribute pfm7 Numeric', ... 
    '@Attribute pfm8 Numeric','@Attribute pfm9 Numeric','@Attribute pfm10 Numeric', ...
    '@Attribute pfm11 Numeric','@Attribute pfm12 Numeric','@Attribute pfm13 Numeric', ...
    '@Attribute pfm14 Numeric','@Attribute pfm15 Numeric','@Attribute pfm16 Numeric', ...
    '@Attribute pfm17 Numeric','@Attribute pfm18 Numeric','@Attribute pfm19 Numeric', ...
    '@Attribute pfm20 Numeric','@Attribute pfm21 Numeric');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute pfr1 Numeric', ...
    '@Attribute pfr2 Numeric','@Attribute pfr3 Numeric','@Attribute pfr4 Numeric', ...
    '@Attribute pfr5 Numeric','@Attribute pfr6 Numeric','@Attribute pfr7 Numeric', ... 
    '@Attribute pfr8 Numeric','@Attribute pfr9 Numeric','@Attribute pfr10 Numeric', ...
    '@Attribute pfr11 Numeric','@Attribute pfr12 Numeric','@Attribute pfr13 Numeric', ...
    '@Attribute pfr14 Numeric','@Attribute pfr15 Numeric','@Attribute pfr16 Numeric', ...
    '@Attribute pfr17 Numeric','@Attribute pfr18 Numeric','@Attribute pfr19 Numeric', ...
    '@Attribute pfr20 Numeric','@Attribute pfr21 Numeric');
fprintf(fid,['%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n' ...
    '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'],'@Attribute pfp1 Numeric', ...
    '@Attribute pfp2 Numeric','@Attribute pfp3 Numeric','@Attribute pfp4 Numeric', ...
    '@Attribute pfp5 Numeric','@Attribute pfp6 Numeric','@Attribute pfp7 Numeric', ... 
    '@Attribute pfp8 Numeric','@Attribute pfp9 Numeric','@Attribute pfp10 Numeric', ...
    '@Attribute pfp11 Numeric','@Attribute pfp12 Numeric','@Attribute pfp13 Numeric', ...
    '@Attribute pfp14 Numeric','@Attribute pfp15 Numeric','@Attribute pfp16 Numeric', ...
    '@Attribute pfp17 Numeric','@Attribute pfp18 Numeric','@Attribute pfp19 Numeric', ...
    '@Attribute pfp20 Numeric','@Attribute pfp21 Numeric');
fprintf(fid,'%s\n','@Attribute light Numeric');
fprintf(fid,'%s\n','@Attribute Time_of_Day Numeric');
fprintf(fid,'%s\n\n','@Attribute Occupants {0,1,2,3,4}');
fprintf(fid,'%s\n','@DATA');

[r,c] = size(big_mat);

for i=1:r
    for j=1:c-2
        fprintf(fid,'%f,',big_mat(i,j));
    end
    fprintf(fid,'%d\n',big_mat(i,j+1));
end


fclose(fid);
